party/views.py
from flask import Blueprint, render_template, request, session, redirect, url_for, abort
import bson


from party.forms import BasicPartyForm, EditPartyForm, CancelPartyForm
from user.decorators import login_required
from party.models import Party
from user.models import User
from utilities.storage import upload_image_file

party_page = Blueprint('party_page', __name__)

@party_page.route('/create', methods=['GET', 'POST'])
@login_required
def create():
    form = BasicPartyForm()
    error = None
    if request.method == 'POST' and form.validate():
        if form.end_datetime.data < form.start_datetime.data:
            error = "A party must end after it starts!"
        if not error:
            user = User.objects.filter(email=session.get('email')).first()
            
            party = Party(
                name=form.name.data,
                place=form.place.data,
                location=[form.lng.data, form.lat.data],
                start_datetime=form.start_datetime.data,
                end_datetime=form.end_datetime.data,
                description=form.description.data,
                host=user.id,
                attendees=[user]
            )
            party.save()
            return redirect(url_for('party_page.edit', id=party.id))
    return render_template('party/create.html', form=form)

@party_page.route('/<id>/edit', methods=['GET', 'POST'])
@login_required
def edit(id):
    try:
        party = Party.objects.filter(id=bson.ObjectId(id)).first()
    except bson.errors.InvalidId:
        abort(404)
        
    user = User.objects.filter(email=session.get('email')).first()
    
    if party and party.host == user.id:
        error = None
        message = None
        form = EditPartyForm(obj=party)
        if request.method == 'POST' and form.validate():
            if form.end_datetime.data < form.start_datetime.data:
                error = 'A party must end after it starts!'
            if not error:
                form.populate_obj(party)
                if form.lng.data and form.lat.data:
                    party.location = [form.lng.data, form.lat.data]
                image_url = upload_image_file(request.files.get('photo'), 'party_photo', str(party.id))
                if image_url:
                    party.party_photo = image_url
                party.save()
                message = 'Party updated'
        return render_template('party/edit.html', form=form, error=error,
                              message=message, party=party)
    else:
        abort(404)

@party_page.route('/<id>/cancel', methods=['GET', 'POST'])
@login_required
def cancel(id):
    try:
        party = Party.objects.filter(id=bson.ObjectId(id)).first()
    except bson.errors.InvalidId:
        abort(404)
    user = User.objects.filter(email=session.get('email')).first()
    
    if party and party.host == user.id and party.cancel == False:
        error = None
        form = CancelPartyForm()
        if request.method == 'POST' and form.validate():
            if form.confirm.data == 'yes':
                party.cancel = True
                party.save()
                return redirect(url_for('party_page.edit', id=party.id))
            else:
                error = 'Say yes if you want to cancel'
        return render_template('party/cancel.html', form=form, error=error, party=party)
    else:
        abort(404)

@party_page.route('/<id>', methods=['GET'])
def public(id):
    try:
        party = Party.objects.filter(id=bson.ObjectId(id)).first()
    except bson.errors.InvalidId:
        abort(404)
        
    if party:
        host = User.objects.filter(id=party.host).first()
        user = User.objects.filter(email=session.get('email')).first()
        return render_template('party/public.html', party=party, host=host, user=user)
    else:
        abort(404)
        
@party_page.route('/<id>/join', methods=['GET'])
@login_required
def join(id):
    user = User.objects.filter(email=session.get('email')).first()
    try:
        party = Party.objects.filter(id=bson.ObjectId(id)).first()
    except bson.errors.InvalidId:
        abort(404)    
    
    if user and party:
        if user not in party.attendees:
            party.attendees.append(user)
            party.save()
        return redirect(url_for('party_page.public', id=id))
    else:
        abort(404)
        
@party_page.route('/<id>/leave', methods=['GET'])
@login_required
def leave(id):
    user = User.objects.filter(email=session.get('email')).first()
    try:
        party = Party.objects.filter(id=bson.ObjectId(id)).first()
    except bson.errors.InvalidId:
        abort(404)   
    
    if user and party:
        if user in party.attendees:
            party.attendees.remove(user)
            party.save()
        return redirect(url_for('party_page.public', id=id))
    else:
        abort(404)

@party_page.route('/manage/<int:party_page_number>', methods=['GET'])
@party_page.route('/manage', methods=['GET'])
@login_required
def manage(party_page_number=1):
    user = User.objects.filter(email=session.get('email')).first()
    if user:
        parties = Party.objects.filter(host=user.id).order_by('-start_datetime').paginate(page=party_page_number, per_page=4)
        return render_template('party/manage.html', parties=parties)
    else:
        abort(404)

@party_page.route('/explore/<int:party_page_number>', methods=['GET'])
@party_page.route('/explore', methods=['GET'])
def explore(party_page_number=1):
    place = request.args.get('place')
    try:
        lng = float(request.args.get('lng'))
        lat = float(request.args.get('lat'))
        parties = Party.objects(location__near=[lng, lat], location__max_distance=10000,
                               cancel=False).order_by('-start_datetime').paginate(page=party_page_number, per_page=4)
        return render_template('party/explore.html', parties=parties, place=place, lng=lng, lat=lat)
    except:
        return render_template('party/explore.html', place=place)

user/views.py
from flask import Blueprint, render_template, request, session, redirect, url_for, abort
import bcrypt
import bson

from party.models import Party
from user.models import User
from user.forms import RegistrationForm, LoginForm, EditProfileForm, PasswordForm
from user.decorators import login_required
from utilities.storage import upload_image_file


user_page = Blueprint('user_page', __name__)

@user_page.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm(request.form)
    error = None
        
    if request.method == 'POST' and form.validate():
        user = User.objects.filter(email=form.email.data.lower()).first()
        if user:
            if bcrypt.checkpw(form.password.data, user.password):
                session['email'] = user.email   
                return redirect(request.args.get('next') or url_for('home'))
            else:
                user = None
        if not user:
            error = 'Your email or password was entered incorrectly'
    return render_template('user/login.html', form=form, error=error)

@user_page.route('/logout')
def logout():
    session.pop('email')
    return redirect(url_for('user_page.login'))

@user_page.route('/signup', methods=['GET', 'POST'])
def signup():
    form = RegistrationForm(request.form)
    if request.method == 'POST' and form.validate():
        salt = bcrypt.gensalt()
        hashed_password = bcrypt.hashpw(form.password.data, salt)
        
        user = User(
            name=form.name.data,
            email=form.email.data.lower(),
            password=hashed_password
        )
        user.save()
        
        return redirect(url_for('user_page.login'))
    return render_template('user/signup.html', form=form)

@user_page.route('/edit', methods=['GET', 'POST'])
@login_required
def edit():
    user = User.objects.filter(email=session['email']).first()
    if user:
        error = None
        message = None
        form = EditProfileForm(obj=user)
        
        if request.method == 'POST' and form.validate():
            if user.email != form.email.data.lower():
                if User.objects.filter(email=form.email.data.lower()).first():
                    error = "Email is already in use"
                else:
                    session['email'] = form.email.data.lower()
            if not error:
                form.populate_obj(user)
                image_url = upload_image_file(request.files.get('image'), 'profile_image', str(user.id))
                print(str(request.files.get('image')))
                if image_url:
                    user.profile_image = image_url
                user.save()
                message = "Profile updated"
                
        return render_template('user/edit.html', user=user, form=form, error=error, message=message)
    else:
        abort(404)
        
@user_page.route('/password', methods=['GET', 'POST'])
@login_required
def password():
    user = User.objects.filter(email=session.get('email')).first()
    if user:
        error = None
        message = None
        form = PasswordForm()
        if request.method == 'POST' and form.validate():
            if bcrypt.checkpw(form.old_password.data, user.password):
                salt = bcrypt.gensalt()
                hashed_password = bcrypt.hashpw(form.new_password.data, salt)
                user.password = hashed_password
                user.save()
                message = 'Password updated'
            else:
                error = 'Your old password was incorrect'
        return render_template('user/password.html', form=form, error=error, message=message)
    else:
        abort(404)

@user_page.route('/<id>/<int:party_page_number>', methods=['GET'])
@user_page.route('/<id>')
def profile(id, party_page_number=1):
    try:
        user = User.objects.filter(id=bson.ObjectId(id)).first()
    except bson.errors.InvalidId:
        abort(404)
    if user:
        parties = Party.objects(attendees__in=[user], cancel=False).order_by('-start_datetime').paginate(page=party_page_number, per_page=4)
        return render_template('user/profile.html', user=user, parties=parties)
    else:
        abort(404)
        

templates/_formhelpers.html
{% macro render_field(field) %}
<div class="form-group">
    {{ field.label }}
    {{ field(**kwargs)|safe }}
    {% if field.errors %}
        <ul class="text-danger">
        {% for error in field.errors %}
            <li>{{ error}}</li>
        {% endfor %}
        </ul>
    {% endif %}
</div>
{% endmacro %}

templates/base.html
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>{% block title %}{% endblock %}</title>

  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">

  <!-- Stylesheets -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">

  <!-- Custom styles for this template -->
  <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
  <style>
    .container {
      padding-top: 100px;
    }
  </style>

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse fixed-top">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    <a class="navbar-brand" href="/">PartyGo</a>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
      <ul class="navbar-nav ml-auto">  
          
        <li class="nav-item {% if request.endpoint == 'party_page.create' %}active{% endif %}">
          <a class="nav-link" href="{{ url_for('party_page.create') }}">Create a Party</a>
        </li>  
        <li class="nav-item {% if request.endpoint == 'party_page.explore' %}active{% endif %}">
          <a class="nav-link" href="{{ url_for('party_page.explore') }}">Explore</a>
        </li> 
        {% if session.email %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" id="navbarsExampleDefault" aria-haspopup="true" aria-expanded="false">{{ session.email }}</a>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="{{ url_for('user_page.edit') }}">Edit Profile</a>
            <a class="dropdown-item" href="{{ url_for('user_page.password') }}">Change Password</a>
            <a class="dropdown-item" href="{{ url_for('party_page.manage') }}">My Parties</a>
          </div>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('user_page.logout') }}">Log out</a>
        </li>
        {% else %}
        <li class="nav-item {% if request.endpoint == 'user_page.login' %}active{% endif %}">
          <a class="nav-link" href="{{ url_for('user_page.login') }}">Log In</a>
        </li>
        <li class="nav-item {% if request.endpoint == 'user_page.signup' %}active{% endif %}">
          <a class="nav-link" href="{{ url_for('user_page.signup') }}">Sign Up</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </nav>

  <!-- Page Content -->
  <div class="container">
    {% block content %}{% endblock %}
  </div>

  <!-- Bootstrap core JavaScript -->
  <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>

  {% block javascript %}{% endblock %}
</body>

</html>

templates/googleapi.html
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA9P9F0ik8CwP0hCoQxvRoVt3NQPvzG1dE&libraries=places&callback=initAutocomplete" async defer></script>

<script>
    function initAutocomplete() {
        // Create the autocomplete object, restricting the search to geographical
        // location types.
        autocomplete = new google.maps.places.Autocomplete(
            /** @type {!HTMLInputElement} */
            (document.getElementById('autocomplete')), {
                types: ['geocode']
            });

        // When the user selects an address from the dropdown, populate the address
        // fields in the form.
        autocomplete.addListener('place_changed', fillInAddress);
    }

    function fillInAddress() {
        // Get the place details from the autocomplete object.
        var place = autocomplete.getPlace();
        document.getElementById('place').value = place.formatted_address;
        document.getElementById('lng').value = place.geometry.location.lng();
        document.getElementById('lat').value = place.geometry.location.lat();
        
    }
</script>